services:
  blog-server:
    env_file: .env
    environment:
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - .:/rails
    ports:
      - "80:80"

