
services:
  blog-server:
    env_file: .env
    environment:
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - .:/rails

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443 
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro


