version: '3'

services:
  blog-server:
    env_file: .env
    environment:
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - .:/rails
    networks:
      - app-network

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443 
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./etc/letsencrypt:/etc/letsencrypt:ro 
      - ./certbot/data:/var/www/certbot

  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    depends_on:
      - nginx
    command: >-
             certonly --reinstall --webroot --webroot-path=/var/www/certbot
             --email contact@zack.fyi --agree-tos --no-eff-email
             -d server.zack.fyi
    volumes:
      - ./etc/letsencrypt:/etc/letsencrypt
      - ./certbot/data:/var/www/certbot
