version: '3'

services:
  blog-server:
    env_file: .env
    environment:
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - .:/rails
    # Remove port 80 exposure (handled by proxy)
    networks:
      - app-network

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - blog-server
    networks:
      - app-network
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt

  certbot:
    image: certbot/certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./nginx:/etc/nginx/conf.d
    command: certonly --noninteractive --agree-tos --email your-email@example.com --webroot -w /var/lib/letsencrypt -d your-domain.com

networks:
  app-network:
    driver: bridge

volumes:
  certbot-etc:
  certbot-var:
