# THIS IS VESTIGIAL, AND NOT RECOMMENDED
# The digital ocean I'm running this on takes *forever* to build this.
# I'm keeping it around in case I get a more powerful server one day.

services:
  blog-server:
    env_file: .env
    environment:
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - .:/rails

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443 
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/live/server.zack.fyi/fullchain.pem:/etc/letsencrypt/live/server.zack.fyi/fullchain.pem:ro
      - /etc/letsencrypt/live/server.zack.fyi/privkey.pem:/etc/letsencrypt/live/server.zack.fyi/privkey.pem:ro


